USE [master]
GO

/****** Object:  Database [BD_Empleados]    Script Date: 06/12/2015 20:14:44 ******/
CREATE DATABASE [BD_Empleados] ON  PRIMARY 
( NAME = N'BD_Empleados', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\BD_Empleados.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_Empleados_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\BD_Empleados_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BD_Empleados] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Empleados].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Empleados] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Empleados] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Empleados] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Empleados] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Empleados] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Empleados] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_Empleados] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Empleados] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Empleados] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Empleados] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Empleados] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Empleados] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Empleados] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Empleados] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Empleados] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Empleados] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_Empleados] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Empleados] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Empleados] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Empleados] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Empleados] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Empleados] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Empleados] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Empleados] SET  READ_WRITE 
GO

ALTER DATABASE [BD_Empleados] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_Empleados] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Empleados] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Empleados] SET DB_CHAINING OFF 
GO

