//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServicesTest.SolicitudesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.SolicitudesWS.Proyecto ProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.SolicitudesWS.SolicitudDetalle[] detalleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.SolicitudesWS.Proyecto Proyecto {
            get {
                return this.ProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProyectoField, value) != true)) {
                    this.ProyectoField = value;
                    this.RaisePropertyChanged("Proyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.SolicitudesWS.SolicitudDetalle[] detalle {
            get {
                return this.detalleField;
            }
            set {
                if ((object.ReferenceEquals(this.detalleField, value) != true)) {
                    this.detalleField = value;
                    this.RaisePropertyChanged("detalle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proyecto", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Proyecto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.SolicitudesWS.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProyectoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.SolicitudesWS.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodProyecto {
            get {
                return this.CodProyectoField;
            }
            set {
                if ((this.CodProyectoField.Equals(value) != true)) {
                    this.CodProyectoField = value;
                    this.RaisePropertyChanged("CodProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProyecto {
            get {
                return this.NombreProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProyectoField, value) != true)) {
                    this.NombreProyectoField = value;
                    this.RaisePropertyChanged("NombreProyecto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudDetalle", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class SolicitudDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadColaborField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.SolicitudesWS.ExperienciaRubro ExperienciaRubroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.SolicitudesWS.Perfil PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SOAPServicesTest.SolicitudesWS.Tecnologia TecnologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadColabor {
            get {
                return this.CantidadColaborField;
            }
            set {
                if ((this.CantidadColaborField.Equals(value) != true)) {
                    this.CantidadColaborField = value;
                    this.RaisePropertyChanged("CantidadColabor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.SolicitudesWS.ExperienciaRubro ExperienciaRubro {
            get {
                return this.ExperienciaRubroField;
            }
            set {
                if ((object.ReferenceEquals(this.ExperienciaRubroField, value) != true)) {
                    this.ExperienciaRubroField = value;
                    this.RaisePropertyChanged("ExperienciaRubro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.SolicitudesWS.Perfil Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfilField, value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOAPServicesTest.SolicitudesWS.Tecnologia Tecnologia {
            get {
                return this.TecnologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.TecnologiaField, value) != true)) {
                    this.TecnologiaField = value;
                    this.RaisePropertyChanged("Tecnologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RucClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodCliente {
            get {
                return this.CodClienteField;
            }
            set {
                if ((this.CodClienteField.Equals(value) != true)) {
                    this.CodClienteField = value;
                    this.RaisePropertyChanged("CodCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocialCliente {
            get {
                return this.RazonSocialClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialClienteField, value) != true)) {
                    this.RazonSocialClienteField = value;
                    this.RaisePropertyChanged("RazonSocialCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RucCliente {
            get {
                return this.RucClienteField;
            }
            set {
                if ((this.RucClienteField.Equals(value) != true)) {
                    this.RucClienteField = value;
                    this.RaisePropertyChanged("RucCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciaRubro", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class ExperienciaRubro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodExperienciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreExperienciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodExperiencia {
            get {
                return this.CodExperienciaField;
            }
            set {
                if ((this.CodExperienciaField.Equals(value) != true)) {
                    this.CodExperienciaField = value;
                    this.RaisePropertyChanged("CodExperiencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreExperiencia {
            get {
                return this.NombreExperienciaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreExperienciaField, value) != true)) {
                    this.NombreExperienciaField = value;
                    this.RaisePropertyChanged("NombreExperiencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePerfilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodPerfil {
            get {
                return this.CodPerfilField;
            }
            set {
                if ((this.CodPerfilField.Equals(value) != true)) {
                    this.CodPerfilField = value;
                    this.RaisePropertyChanged("CodPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePerfil {
            get {
                return this.NombrePerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePerfilField, value) != true)) {
                    this.NombrePerfilField = value;
                    this.RaisePropertyChanged("NombrePerfil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tecnologia", Namespace="http://schemas.datacontract.org/2004/07/JavaNetServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Tecnologia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodTecnologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTecnologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodTecnologia {
            get {
                return this.CodTecnologiaField;
            }
            set {
                if ((this.CodTecnologiaField.Equals(value) != true)) {
                    this.CodTecnologiaField = value;
                    this.RaisePropertyChanged("CodTecnologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTecnologia {
            get {
                return this.NombreTecnologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTecnologiaField, value) != true)) {
                    this.NombreTecnologiaField = value;
                    this.RaisePropertyChanged("NombreTecnologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SolicitudesWS.ISolicitudes")]
    public interface ISolicitudes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/CrearSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/CrearSolicitudResponse")]
        SOAPServicesTest.SolicitudesWS.Solicitud CrearSolicitud(int codProyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/CrearSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/CrearSolicitudResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud> CrearSolicitudAsync(int codProyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/CrearSolicitudDetalle", ReplyAction="http://tempuri.org/ISolicitudes/CrearSolicitudDetalleResponse")]
        SOAPServicesTest.SolicitudesWS.SolicitudDetalle CrearSolicitudDetalle(int codigo, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/CrearSolicitudDetalle", ReplyAction="http://tempuri.org/ISolicitudes/CrearSolicitudDetalleResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.SolicitudDetalle> CrearSolicitudDetalleAsync(int codigo, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/ObtenerSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/ObtenerSolicitudResponse")]
        SOAPServicesTest.SolicitudesWS.Solicitud ObtenerSolicitud(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/ObtenerSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/ObtenerSolicitudResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud> ObtenerSolicitudAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/ModificarSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/ModificarSolicitudResponse")]
        SOAPServicesTest.SolicitudesWS.Solicitud ModificarSolicitud(int codigo, int codProyecto, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/ModificarSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/ModificarSolicitudResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud> ModificarSolicitudAsync(int codigo, int codProyecto, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/EliminarSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/EliminarSolicitudResponse")]
        void EliminarSolicitud(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/EliminarSolicitud", ReplyAction="http://tempuri.org/ISolicitudes/EliminarSolicitudResponse")]
        System.Threading.Tasks.Task EliminarSolicitudAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/ListarSolicitudes", ReplyAction="http://tempuri.org/ISolicitudes/ListarSolicitudesResponse")]
        SOAPServicesTest.SolicitudesWS.Solicitud[] ListarSolicitudes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudes/ListarSolicitudes", ReplyAction="http://tempuri.org/ISolicitudes/ListarSolicitudesResponse")]
        System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud[]> ListarSolicitudesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudesChannel : SOAPServicesTest.SolicitudesWS.ISolicitudes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudesClient : System.ServiceModel.ClientBase<SOAPServicesTest.SolicitudesWS.ISolicitudes>, SOAPServicesTest.SolicitudesWS.ISolicitudes {
        
        public SolicitudesClient() {
        }
        
        public SolicitudesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOAPServicesTest.SolicitudesWS.Solicitud CrearSolicitud(int codProyecto) {
            return base.Channel.CrearSolicitud(codProyecto);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud> CrearSolicitudAsync(int codProyecto) {
            return base.Channel.CrearSolicitudAsync(codProyecto);
        }
        
        public SOAPServicesTest.SolicitudesWS.SolicitudDetalle CrearSolicitudDetalle(int codigo, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario) {
            return base.Channel.CrearSolicitudDetalle(codigo, cantidadColabor, codPerfil, codTecnologia, codExperienciaRubro, comentario);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.SolicitudDetalle> CrearSolicitudDetalleAsync(int codigo, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario) {
            return base.Channel.CrearSolicitudDetalleAsync(codigo, cantidadColabor, codPerfil, codTecnologia, codExperienciaRubro, comentario);
        }
        
        public SOAPServicesTest.SolicitudesWS.Solicitud ObtenerSolicitud(int codigo) {
            return base.Channel.ObtenerSolicitud(codigo);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud> ObtenerSolicitudAsync(int codigo) {
            return base.Channel.ObtenerSolicitudAsync(codigo);
        }
        
        public SOAPServicesTest.SolicitudesWS.Solicitud ModificarSolicitud(int codigo, int codProyecto, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario) {
            return base.Channel.ModificarSolicitud(codigo, codProyecto, cantidadColabor, codPerfil, codTecnologia, codExperienciaRubro, comentario);
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud> ModificarSolicitudAsync(int codigo, int codProyecto, int cantidadColabor, int codPerfil, int codTecnologia, int codExperienciaRubro, string comentario) {
            return base.Channel.ModificarSolicitudAsync(codigo, codProyecto, cantidadColabor, codPerfil, codTecnologia, codExperienciaRubro, comentario);
        }
        
        public void EliminarSolicitud(int codigo) {
            base.Channel.EliminarSolicitud(codigo);
        }
        
        public System.Threading.Tasks.Task EliminarSolicitudAsync(int codigo) {
            return base.Channel.EliminarSolicitudAsync(codigo);
        }
        
        public SOAPServicesTest.SolicitudesWS.Solicitud[] ListarSolicitudes() {
            return base.Channel.ListarSolicitudes();
        }
        
        public System.Threading.Tasks.Task<SOAPServicesTest.SolicitudesWS.Solicitud[]> ListarSolicitudesAsync() {
            return base.Channel.ListarSolicitudesAsync();
        }
    }
}
