//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServicesTest.GeneracionSolicitudWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudDetalle", Namespace="http://schemas.datacontract.org/2004/07/SolicitudService.Dominio")]
    [System.SerializableAttribute()]
    public partial class SolicitudDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadColaborField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codExperienciaRubroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codTecnologiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadColabor {
            get {
                return this.CantidadColaborField;
            }
            set {
                if ((this.CantidadColaborField.Equals(value) != true)) {
                    this.CantidadColaborField = value;
                    this.RaisePropertyChanged("CantidadColabor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codExperienciaRubro {
            get {
                return this.codExperienciaRubroField;
            }
            set {
                if ((object.ReferenceEquals(this.codExperienciaRubroField, value) != true)) {
                    this.codExperienciaRubroField = value;
                    this.RaisePropertyChanged("codExperienciaRubro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPerfil {
            get {
                return this.codPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.codPerfilField, value) != true)) {
                    this.codPerfilField = value;
                    this.RaisePropertyChanged("codPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codTecnologia {
            get {
                return this.codTecnologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.codTecnologiaField, value) != true)) {
                    this.codTecnologiaField = value;
                    this.RaisePropertyChanged("codTecnologia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyExcepcion", Namespace="http://schemas.datacontract.org/2004/07/SolicitudService.Dominio")]
    [System.SerializableAttribute()]
    public partial class MyExcepcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesssageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messsage {
            get {
                return this.MesssageField;
            }
            set {
                if ((object.ReferenceEquals(this.MesssageField, value) != true)) {
                    this.MesssageField = value;
                    this.RaisePropertyChanged("Messsage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneracionSolicitudWS.ICrearSolicitud")]
    public interface ICrearSolicitud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrearSolicitud/GenerarSolicitud", ReplyAction="http://tempuri.org/ICrearSolicitud/GenerarSolicitudResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SOAPServicesTest.GeneracionSolicitudWS.MyExcepcion), Action="http://tempuri.org/ICrearSolicitud/GenerarSolicitudMyExcepcionFault", Name="MyExcepcion", Namespace="http://schemas.datacontract.org/2004/07/SolicitudService.Dominio")]
        int GenerarSolicitud(int codCliente, int codProyecto, SOAPServicesTest.GeneracionSolicitudWS.SolicitudDetalle[] detalleSolicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrearSolicitud/GenerarSolicitud", ReplyAction="http://tempuri.org/ICrearSolicitud/GenerarSolicitudResponse")]
        System.Threading.Tasks.Task<int> GenerarSolicitudAsync(int codCliente, int codProyecto, SOAPServicesTest.GeneracionSolicitudWS.SolicitudDetalle[] detalleSolicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrearSolicitudChannel : SOAPServicesTest.GeneracionSolicitudWS.ICrearSolicitud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrearSolicitudClient : System.ServiceModel.ClientBase<SOAPServicesTest.GeneracionSolicitudWS.ICrearSolicitud>, SOAPServicesTest.GeneracionSolicitudWS.ICrearSolicitud {
        
        public CrearSolicitudClient() {
        }
        
        public CrearSolicitudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrearSolicitudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrearSolicitudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrearSolicitudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GenerarSolicitud(int codCliente, int codProyecto, SOAPServicesTest.GeneracionSolicitudWS.SolicitudDetalle[] detalleSolicitud) {
            return base.Channel.GenerarSolicitud(codCliente, codProyecto, detalleSolicitud);
        }
        
        public System.Threading.Tasks.Task<int> GenerarSolicitudAsync(int codCliente, int codProyecto, SOAPServicesTest.GeneracionSolicitudWS.SolicitudDetalle[] detalleSolicitud) {
            return base.Channel.GenerarSolicitudAsync(codCliente, codProyecto, detalleSolicitud);
        }

        internal int GenerarSolicitud(int codCliente, int codProyecto, System.Collections.Generic.List<SolicitudDetalle> listaDetalle)
        {
            throw new NotImplementedException();
        }
    }
}
